apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-php-fpm
  namespace: default
  labels:
    app.kubernetes.io/instance: example-app-php-fpm
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/chart-name: php-fpm
      app.kubernetes.io/release-name: example-app-php-fpm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/chart-name: php-fpm
        app.kubernetes.io/instance: example-app-php-fpm
        app.kubernetes.io/release-name: example-app-php-fpm
        app.metadata.io/version: v1-2-1
    spec:
      containers:
        - name: php-fpm
          image: wirwolf/php-bug-12600:latest
          imagePullPolicy: IfNotPresent
#          env:
#            - name: PHP_FPM_GLOBAL_LOG_LEVEL
#              value: 'debug'
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - >-
                    echo "Stopping container by k8s...">/proc/1/fd/1 &&
                    /bin/kill -QUIT 1
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 60m
              memory: 200Mi
            requests:
              cpu: 30m
              memory: 50Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/chart-name: php-fpm
                    app.kubernetes.io/release-name: example-app-php-fpm
                topologyKey: kubernetes.io/hostname
              weight: 1
